site_name: Dokumentasi SentinelOne EDR
site_description: Dokumentasi sederhana untuk implementasi dan pengelolaan SentinelOne EDR
site_author: Salman Mustapa
site_url: https://salman-mustapa.github.io/s1-docs/

theme:
  name: material
  language: id
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Page tree
nav:
  - Overview:
    - Home: index.md
    - SentinelCtl Commands: commands/sentinelctl-reference.md
  - Installation and Configuration:
    - Install EDR to Server/Endpoint: installation/edr-install.md
    - File/Folder/App Exclusion from EDR: installation/edr-exclusion.md
    - Update EDR Patch to Endpoint (Sensor Update): installation/sensor-update.md
  - System Monitoring:
    - Resource Utilization: monitoring/resource-utilization.md
    - Bandwidth Utilization: monitoring/bandwidth-utilization.md
  - Management:
    - Uninstall EDR: management/uninstall-edr.md
  - Integration:
    - Integration to 3rd Party: integration/third-party-integration.md
  - Security Operations:
    - Real-time Telemetry: security/real-time-telemetry.md
    - Threat Detection: security/threat-detection.md
    - Threat Hunting: security/threat-hunting.md
    - Offline Detection/Response: security/offline-detection-response.md
  - Testing & Validation:
    - Testing Overview: testing/testing-overview.md
    - Kategori A - Real-Time Protection: testing/kategori-a-realtime.md
    - Kategori B - Offline Scenarios: testing/kategori-b-offline.md
    - Kategori C - Operational Resilience: testing/kategori-c-operational.md
    - Kategori D - Security Hardening: testing/kategori-d-security.md
    - Kategori E - Performance Impact: testing/kategori-e-performance.md
    - Kategori F - Integration Testing: testing/kategori-f-integration.md
    - Windows Server Testing:
      - Windows Overview: testing/windows/windows-overview.md
      - Windows Offline Testing: testing/windows/windows-offline.md
      - Windows Performance Testing: testing/windows/windows-performance.md
      - Windows Enterprise Testing: testing/windows/windows-enterprise.md
    - Linux Server Testing:
      - Linux Overview: testing/linux/linux-overview.md
      - Linux Offline Testing: testing/linux/linux-offline.md
      - Linux Performance Testing: testing/linux/linux-performance.md
      - Linux Container Testing: testing/linux/linux-containers.md
    - Cross-Platform Scenarios: testing/cross-platform/cross-platform-testing.md
  - Contoh Gambar & Visual: example-images.md

# Extra CSS and JavaScript
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mermaid.js

# Extra
repo_url: https://github.com/salman-mustapa/s1-docs
repo_name: salman-mustapa/s1-docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/salman-mustapa
    - icon: fontawesome/regular/envelope
      link: mailto:salman.mustapa@dikstrasolusi.com
  generator: false  # Hapus "Made with Material for MkDocs"

copyright: |
  <p>
    © 2025 <a href="https://github.com/salman-mustapa" target="_blank">Salman Mustapa</a>. All rights reserved.
    <br>
    <small>
      Licensed under <a href="https://github.com/salman-mustapa/s1-docs/blob/main/LICENSE" target="_blank">MIT License</a>
    </small>
  </p>
